CREATE DATABASE  IF NOT EXISTS TU_PSI;
USE TU_PSI;

CREATE TABLE RAMA_DE_PSICOLOGIA (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_RAMA VARCHAR(45)
);

CREATE TABLE UBICACION(
ID INT PRIMARY KEY AUTO_INCREMENT,
PROVINCIA VARCHAR(45),
CIUDAD VARCHAR(30),
CALLE VARCHAR (45),
ALTURA VARCHAR(10)
);

CREATE TABLE PACIENTE_CONSULTOR(
DNI_PACIENTE INT UNIQUE NOT NULL,
NOMBRE VARCHAR (100) NOT NULL,
APELLIDO VARCHAR(100),
EMAIL VARCHAR(45),
TELEFONO BIGINT,
FECHA_NAC DATE,
SEXO VARCHAR (50),
UBICACION_ID INT,
CONSTRAINT PK_ID_PACIENTE PRIMARY KEY (DNI_PACIENTE),
CONSTRAINT FK_UBICACION FOREIGN KEY (UBICACION_ID) REFERENCES UBICACION (ID));

CREATE TABLE PSICOLOGO(
DNI INT UNIQUE NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR (100) NOT NULL,
CONTRASEÑA VARCHAR(8),
EMAIL VARCHAR(45),
TELEFONO BIGINT,
UBICACION INT,
RAMA_DE_PSICOLOGIA INT,
PACIENTE_CONSULTOR INT,
CONSTRAINT PK_DNI PRIMARY KEY (DNI),
CONSTRAINT FK_UBIC_ID FOREIGN KEY (UBICACION) REFERENCES UBICACION (ID),
CONSTRAINT FK_RAMA_PSICOLOGIA FOREIGN KEY (RAMA_DE_PSICOLOGIA) REFERENCES RAMA_DE_PSICOLOGIA (ID),
CONSTRAINT FK_PACIENTE_CONSULTOR FOREIGN KEY (PACIENTE_CONSULTOR) REFERENCES PACIENTE_CONSULTOR (DNI_PACIENTE));





