CREATE DATABASE  IF NOT EXISTS TU_PSI;
USE TU_PSI;

CREATE TABLE TIPOS_DE_TERAPIA(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_RAMA VARCHAR(45)
);

CREATE TABLE UBICACION(
ID INT PRIMARY KEY AUTO_INCREMENT,
PROVINCIA VARCHAR(45)
);

CREATE TABLE PACIENTE_CONSULTOR(
DNI_PACIENTE INT UNIQUE NOT NULL,
NOMBRE VARCHAR (100) NOT NULL,
APELLIDO VARCHAR(100),
EMAIL VARCHAR(45),
TELEFONO BIGINT,
FECHA_NAC DATE,
SEXO VARCHAR (50),
UBICACION_ID INT,
CONSTRAINT PK_ID_PACIENTE PRIMARY KEY (DNI_PACIENTE),
CONSTRAINT FK_UBICACION FOREIGN KEY (UBICACION_ID) REFERENCES UBICACION (ID));

CREATE TABLE PSICOLOGO(
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR (100) NOT NULL,
SEXO VARCHAR(15) NOT NULL,
CUIL INT UNIQUE NOT NULL,
FECHA_DE_NACIOMIENTO DATE,
COLEGIO_REGULADOR VARCHAR(100) NOT NULL,
EMAIL VARCHAR(45),
CONTRASEÑA VARCHAR(8),
TELEFONO BIGINT,
UBICACION INT,
TIPOS_DE_TERAPIA INT,
PACIENTE_CONSULTOR INT,
CONSTRAINT PK_DNI PRIMARY KEY (CUIL),
CONSTRAINT FK_UBIC_ID FOREIGN KEY (UBICACION) REFERENCES UBICACION (ID),
CONSTRAINT FK_TIPOS_DE_TERAPIA FOREIGN KEY (TIPOS_DE_TERAPIA) REFERENCES TIPOS_DE_TERAPIA(ID),
CONSTRAINT FK_PACIENTE_CONSULTOR FOREIGN KEY (PACIENTE_CONSULTOR) REFERENCES PACIENTE_CONSULTOR (DNI_PACIENTE));





